version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: geophoto-app-main:latest
    container_name: geophoto-web-main
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      
    restart: unless-stopped